### ISSUE TITLE
Quaternion.CreateRotationFromAToB causing NaN

### ISSUE THREAD

**Issue by sam2** [ara3d/Math3D#30]
There is an issue in `Quaternion.CreateRotationFromAToB` on [line 152](https://github.com/vimaec/Math3D/blob/f3f384aff8019b027c1f33b369abeac7735ef8ff/src/Quaternion.cs#L152) where the value of `fromA.Dot(toB)` can be greater than 1, causing NaN.

example input: 
{Vector3(X = 0.57731324, Y = 0.57728577, Z = 0.5774519)}
{Vector3(X = 0.57738256, Y = 0.57728577, Z = 0.57738256)} 
gives
1.00000012

suggest clamping that value

**Comment by mavimaec** [comment]
The fix has been included in the Vim.Math3D NuGet package v1.6.1
